### ISSUE TITLE
Airmon-ng binary?

### ISSUE THREAD

**Issue by mhsjlw** [kriswebdev/android_aircrack#2]
I need to use airmon-ng on my android device, but I can't find it in the bin folder, how can I compile it or download a pre-compiled airmon-ng binary?

Thanks

**Comment by kriswebdev** [comment]
Airmon-ng is a script, not a binary.

It is device specific, and not meant to be used on Android.

To enable the wireless monitor mode, you must follow the [README](https://github.com/kriswebdev/android_aircrack/blob/master/README.md) instructions: Either you have a device with a broadcom 4329 or 4330 chipset, and that's covered by the README, or you don't and you must use an external WiFi USB stick with monitor mode support. If you're in this last case, you need to find a compatible WiFi USB stick and a guide to install it and enable it on Android => Google.
