### ISSUE TITLE
how to use this in android App building

### ISSUE THREAD

**Issue by aksharora** [kriswebdev/android_aircrack#3]

**Comment by kriswebdev** [comment]
This is not Java code, this is C code. It is compiled using [NDK](https://developer.android.com/ndk/index.html), preferably through CyanogenMod ROM build system, not through Android Studio or similar. It generates an executable that can be run from a terminal.

To integrate it into an Android app, you'd better get the pre-compiled binaries and run them through [Android-Terminal-Emulator](https://github.com/jackpal/Android-Terminal-Emulator) with JavaInstaller Execpty. That's what I did for [PwnAir](http://forum.xda-developers.com/showthread.php?t=2760170).

By the way, I won't release PwnAir source code and I won't make a detailed guide for HowTo create a GUI around Aircrack. If you're not used to Android app development and not patient, don't expect it to be easy.

Anyway, you'll have to get the monitor-mode firmware and driver and install it. That's not something an app can automate easily. The kernel driver needs to be flashed and it is device & ROM specific. You'd better install the proper driver and firmware manually.
