### ISSUE TITLE
Binaries need to be run on a rooted device?

### ISSUE THREAD

**Issue by jesmith0** [kriswebdev/android_aircrack#5]
Does these binaries need to be run on a rooted device in order to work?

**Comment by kriswebdev** [comment]
More than being root, you need a kernel that includes a monitor-mode firmware and driver.

And after that yes, airmon-ng needs root.

From https://www.aircrack-ng.org/doku.php?id=airmon-ng :
>  Also, don't forget you need to be root to use airmon-ng
